version: '3.8'

services:
  # MLflow Tracking Server
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: fraud-detection-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
      - ./models:/app/models
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=./mlruns
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ./mlruns
      --host 0.0.0.0
      --port 5000
    networks:
      - fraud-detection-network
    restart: unless-stopped

  # Fraud Detection API
  fraud-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fraud-detection-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./configs:/app/configs
      - ./dataset:/app/dataset
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - ENVIRONMENT=production
    depends_on:
      - mlflow-server
    command: >
      uvicorn src.api:app
      --host 0.0.0.0
      --port 8000
    networks:
      - fraud-detection-network
    restart: unless-stopped

networks:
  fraud-detection-network:
    driver: bridge
